Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 09/04/2022
Var
Numero : inteiro


Inicio
numero <-0

enquanto numero <= 55 faca
         numero <- numero + 1
         Escreval ("Numero: ", numero)
         Escreval ("*************")
fimenquanto
         Escreval ("Término")

Fimalgoritmo